### ISSUE TITLE
怎么用来 拦截页面呢  可以加一个你的联系方式吗

### ISSUE THREAD

**Issue by xuhaihzou** [coppyC/remax-router#3]

**Comment by coppyC** [comment]
这个只能是api层面的拦截，像物理返回键和默认导航栏上的返回是拦截不到的。
如果不是以上这两种拦截，或许我可以帮到你

**Comment by xuhaihzou** [comment]
需求是  进入小程序的时候向后台发起请求，拿到鉴权结果，如果是非vip用户就不让他进入主页面

**Comment by coppyC** [comment]
remax钉钉群里面coppy就是我
